### ISSUE TITLE
[Bug] 1.4.2 cannot import name 'AC200L'

### ISSUE THREAD

**Issue by chebedewel** [bluetti-community/bluetti-home-assistant#57]
### Is there an existing issue for this?

- [x] I searched and didn't find an existing issue for this problem

### Home Assistant Version

2026.8.3

### BLUETTI Integration Version

1.4.2

### What device are you using?

EP2000

### Describe the bug

After updating to 1.4.2 from 1.4.0 (via HACS) and rebooting the integration doe not start any more
Here is a part of the logs :
`ImportError: cannot import name 'AC200L' from 'bluetti_modbus_lib' (/usr/local/lib/python3.14/site-packages/bluetti_modbus_lib/__init__.py). Did you mean: 'AC500'?`

### To Reproduce

1. upgrade to 1.4.2
2. reboot

### Expected Behaviour

it should start

### Diagnostics dump (if the issue is about missing/wrong data)

```json
Cannot download diagnostics as the integration does not load.

File "/config/custom_components/bluetti/modbus_coordinator.py", line 9, in <module>
    from bluetti_modbus_lib import AC200L, AC500, EP2000, Balco260, Balco500, SMeter
ImportError: cannot import name 'AC200L' from 'bluetti_modbus_lib' (/usr/local/lib/python3.14/site-packages/bluetti_modbus_lib/__init__.py). Did you mean: 'AC500'?
```

**Comment by chpego** [comment]
Thank you for the report - and sorry, that one is on us. 1.4.1 started importing a device class that only exists in bluetti-modbus 0.22.0 and later, while the integration only asks Home Assistant for 0.19.3 or later; Home Assistant never upgrades a library that already satisfies what is asked, so any install whose library predated that (yours, from 1.4.0) lost the whole integration at load - cloud included, whether local Modbus was used or not.

[1.4.3](https://github.com/bluetti-community/bluetti-home-assistant/releases/tag/1.4.3) no longer imports any device class from that library at all, and a test keeps it that way; the fix is verified against the older library versions. Update through HACS and restart Home Assistant - nothing else to do. Please reopen if it still fails.
